apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd-thanhlam
spec:
  project: platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.3
    helm:
      values: |
        config:
          argocd:
            serverAddress: argocd-server.argocd-thanhlam.svc
            grpcWeb: true
            insecure: true
          git:
            user: argocd-image-updater
            email: argocd-image-updater@thanhlam.online
          registries:
            - name: Docker Hub
              api_url: https://registry-1.docker.io
              prefix: docker.io
              default: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-thanhlam
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
