config:
  argocd:
    serverAddress: argocd-server.argocd-thanhlam.svc
    grpcWeb: true
    insecure: true
  git:
    user: argocd-image-updater
    email: argocd-image-updater@thanhlam.online
  registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      prefix: docker.io
      default: true
    - name: registry.thanhlam.online
      api_url: https://registry.thanhlam.online
      prefix: registry.thanhlam.online
      insecure: false
      credentials: pullsecret:lab-thanhlam/registry-pull-secret
