namespace:
  create: true
  name: lab2

replicaCount: 2

image:
  repository: thanhlamcode/freelance-agency-template
  tag: 8e3141b2fec20b9739701ea5a19ff05307db2456
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: lab2.thanhlam.online
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

readinessProbe:
  path: /
  initialDelaySeconds: 2
