{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gea.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | default "1m" }}
  secretStoreRef:
    name: {{ .Values.secrets.storeName | default "vault-backend" }}
    kind: {{ .Values.secrets.storeKind | default "SecretStore" }}
  target:
    name: {{ .Values.secrets.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.secrets.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.secrets.vaultPath }}
        property: {{ . }}
  {{- end }}
{{- end }}